version: '3.3'

services:
  web:
    restart: always
    build:
      context: .
    command: /src/venv/bin/gunicorn BcraftStatistic.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/home/app/web
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: